### ISSUE TITLE
kuboard-v3 pod启动异常

### ISSUE THREAD

**Issue by Axm11** [eip-work/kuboard-press#306]
安装环境：
sealos + k8s v1.18.20 
kuboard部署方式，使用在线安装：kubectl apply -f https://addons.kuboard.cn/kuboard/kuboard-v3.yaml
pod启动情况：
NAME                          READY   STATUS             RESTARTS   AGE
kuboard-etcd-9qjl7            1/1     Running            0          17m
kuboard-etcd-s6shk            1/1     Running            0          17m
kuboard-etcd-wvrsn            1/1     Running            0          17m
kuboard-v3-5f46589bcf-jm2xx   0/1     CrashLoopBackOff   7          17m

kuboard-v3 pod截取部分错误日志如下：
`设置日志级别为 info
[LOG] 2022/01/26 - 14:21:50.302   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/audit-policy-once.yaml
[LOG] 2022/01/26 - 14:21:50.307   | /initializekuboard.processEtcdObject                         120 |  info |  - 忽略对象：KuboardAuditPolicy GLOBAL/GLOBAL
[LOG] 2022/01/26 - 14:21:50.307   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/bran-settings-once.yaml
[LOG] 2022/01/26 - 14:21:50.314   | /initializekuboard.processEtcdObject                         120 |  info |  - 忽略对象：KuboardBrandSettings GLOBAL/KuboardBrandSettings
[LOG] 2022/01/26 - 14:21:50.315   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/login-policy-once.yaml
[LOG] 2022/01/26 - 14:21:50.318   | /initializekuboard.processEtcdObject                         120 |  info |  - 忽略对象：KuboardLoginPolicySettings GLOBAL/KuboardLoginPolicySettings
[LOG] 2022/01/26 - 14:21:50.318   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/roles.yaml
[LOG] 2022/01/26 - 14:21:50.322   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthRole GLOBAL/administrator
[LOG] 2022/01/26 - 14:21:50.335   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthRole GLOBAL/viewer
[LOG] 2022/01/26 - 14:21:50.347   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthRole GLOBAL/authenticated
[LOG] 2022/01/26 - 14:21:50.358   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthRole GLOBAL/anonymous
[LOG] 2022/01/26 - 14:21:50.370   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthRole GLOBAL/sso-user
[LOG] 2022/01/26 - 14:21:50.380   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/user.yaml
[LOG] 2022/01/26 - 14:21:50.382   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthUser GLOBAL/admin
[LOG] 2022/01/26 - 14:21:50.392   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthGroup GLOBAL/administrators
[LOG] 2022/01/26 - 14:21:50.403   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthUserInGroup GLOBAL/admin.administrators
[LOG] 2022/01/26 - 14:21:50.418   | /initializekuboard.processEtcdObject                         122 |  info |  - 更新对象：KuboardAuthGlobalRoleBinding GLOBAL/group.administrators.administrator
[LOG] 2022/01/26 - 14:21:50.433   | /initializekuboard.InitializeDefaultCluster                   28 |  info | 【默认集群】Kuboard 安装在 K8S 中，校验是否需要初始化默认集群...
[LOG] 2022/01/26 - 14:21:50.437   | /initializekuboard.InitializeDefaultCluster                   45 |  info | 【默认集群】已存在，跳过初始化默认集群的过程
[LOG] 2022/01/26 - 14:21:50.437   | /audit/audit_common.questDbDriverURI                          31 |  info | QuestDB连接参数: postgresql://admin:quest@127.0.0.1:8812/qdb
[LOG] 2022/01/26 - 14:21:50.438   | main.main                                                    113 |  info | 使用 http, 端口: 80
[LOG] 2022/01/26 - 14:21:50.439   | /audit/audit_runtime.doInit.func1                            105 | warning | 连接 QuestDB 失败，5秒后重试 runtime error: invalid memory address or nil pointer dereference
[LOG] 2022/01/26 - 14:21:50.454   | /audit/audit_install.InstallQuestDb                           26 | warning | 未找到 kuboard-questdb 容器组，尝试创建 kuboard-questdb Deployment
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: index out of range [0] with length 0
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd44046]

goroutine 112 [running]:
github.com/shaohq/kuboard/server/audit/audit_install.createQuestdbDeployment()
	/usr/src/kuboard/server/audit/audit_install/audit_install.go:84 +0x2405
github.com/shaohq/kuboard/server/audit/audit_install.InstallQuestDb()
	/usr/src/kuboard/server/audit/audit_install/audit_install.go:27 +0x92a
github.com/shaohq/kuboard/server/audit/audit_runtime.doInit.func1()
	/usr/src/kuboard/server/audit/audit_runtime/queue.go:108 +0xe5
panic(0x109c760, 0x231ce60)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/jackc/pgx/v4.(*Conn).IsClosed(...)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:328
github.com/jackc/pgx/v4.(*Conn).Close(0x0, 0x1393470, 0xc0001aa020, 0x0, 0x0)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:251 +0x26
panic(0x109c760, 0x231ce60)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/jackc/pgx/v4.(*Conn).exec(0x0, 0x1393470, 0xc0001aa020, 0x124d2e0, 0x29d, 0x0, 0x0, 0x0, 0xc001219f50, 0x0, ...)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:427 +0x29
github.com/jackc/pgx/v4.(*Conn).Exec(0x0, 0x1393470, 0xc0001aa020, 0x124d2e0, 0x29d, 0x0, 0x0, 0x0, 0xc0001ae480, 0x580000c001394150, ...)
	/go/pkg/mod/github.com/jackc/pgx/v4@v4.11.0/conn.go:410 +0xc6
github.com/shaohq/kuboard/server/audit/audit_runtime.doInit()
	/usr/src/kuboard/server/audit/audit_runtime/queue.go:144 +0xfb
github.com/shaohq/kuboard/server/audit/audit_runtime.InitQuestDB()
	/usr/src/kuboard/server/audit/audit_runtime/queue.go:93 +0xb4
github.com/shaohq/kuboard/server/audit/audit_runtime.InitAuditLogger()
	/usr/src/kuboard/server/audit/audit_runtime/runtime.go:23 +0x65
created by main.main
	/usr/src/kuboard/server/kuboard-server.go:83 +0x2b1`

问题：我该如何修复，或需要提供哪些信息？

**Comment by Axm11** [comment]
已修复。
镜像没更新，看了下官方的更新历史，然后用这个部署吧
kubectl apply -f https://addons.kuboard.cn/kuboard/kuboard-v3.yaml
