### ISSUE TITLE
请问docker方式部署如下报错可能原因是什么：| error | 认证模块初始化失败

### ISSUE THREAD

**Issue by zouchengfang** [eip-work/kuboard-press#512]
[LOG] 2024/03/27 - 14:24:23.257   | /login.AddLoginRoutes                                         28 | error | 认证模块初始化失败：Get "http://127.0.0.1:5556/sso/.well-known/openid-configuration": dial tcp 127.0.0.1:5556: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xd74bd7]
goroutine 1 [running]:
github.com/coreos/go-oidc.(*Provider).Verifier(...)
	/usr/src/kuboard/third-party/go-oidc/verify.go:111
github.com/shaohq/kuboard/server/login.AddLoginRoutes(0xc000583a00)
	/usr/src/kuboard/server/login/login.go:30 +0xf7
main.getRoutes()
	/usr/src/kuboard/server/kuboard-server.go:193 +0x345
main.main()
	/usr/src/kuboard/server/kuboard-server.go:65 +0x185
启动 kuboard-server 失败，此问题通常是因为 Etcd 未能及时启动或者连接不上，系统将在 15 秒后重新尝试：
  1. 如果您使用 docker run 的方式运行 Kuboard，请耐心等候一会儿或者执行 docker restart kuboard；
  2. 如果您将 Kuboard 安装在 Kubernetes 中，请检查 kuboard/kuboard-etcd 是否正常启动

**Comment by DJL1109** [comment]
我也遇到了，不知道怎么处理

**Comment by DJL1109** [comment]
进入kuboard 容器里面手动执行etcd & 命令启动etcd服务就可以，然后kuboard才能正常访问

**Comment by tianml07** [comment]
我也遇到这种情况了，在kuboard 容器里面手动执行etcd &  提示2380端口已存在，

**Comment by iexxk** [comment]
通过修改vim /etc/kubernetes/manifests/kuboard.yaml里面的探针时间，改为60s启动成功了
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /kuboard-resources/version.json
          port: 80
          scheme: HTTP
        initialDelaySeconds: 60 #原来是30s,修改为60s
