### ISSUE TITLE
Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl

### ISSUE THREAD

**Issue by super-vip** [eip-work/kuboard-press#520]
```
使用如下参数启动 Kuboard
DB_DRIVER=com.mysql.cj.jdbc.Driver
DB_URL="jdbc:mysql://10.200.200.23:3306/kuboard?serverTimezone=Asia/Shanghai"
DB_USERNAME=kuboard
JVM_OPTIONS=
java  -jar ./kuboard-server.jar
11:11:14,553 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@c055c54 - URL [jar:nested:/app/kuboard-server.jar/!BOOT-INF/classes/!/logback-spring.xml] is not of type file
11:11:14,620 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.turbo.MDCValueLevelPair] for [MDCValueLevelPair] property
11:11:14,621 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.turbo.MDCValueLevelPair] for [MDCValueLevelPair] property
11:11:14,621 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.turbo.MDCValueLevelPair] for [MDCValueLevelPair] property
11:11:14,621 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.turbo.MDCValueLevelPair] for [MDCValueLevelPair] property
11:11:14,622 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [stdout]
11:11:14,622 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:11:14,622 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:11:14,632 |-WARN in ch.qos.logback.core.model.processor.AppenderModelHandler - Appender named [stderr] not referenced. Skipping further processing.
11:11:14,632 |-WARN in ch.qos.logback.core.model.processor.AppenderModelHandler - Appender named [auditLog] not referenced. Skipping further processing.
11:11:14,633 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.springframework] to INFO
11:11:14,633 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating INFO level on Logger[org.springframework] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.springframework] to true
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.springframework.security] to INFO
11:11:14,636 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating INFO level on Logger[org.springframework.security] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.springframework.security] to true
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.springframework.cache] to INFO
11:11:14,636 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating INFO level on Logger[org.springframework.cache] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.springframework.cache] to true
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [io.swagger] to INFO
11:11:14,636 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating INFO level on Logger[io.swagger] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [io.swagger] to true
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.mariadb] to INFO
11:11:14,636 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating INFO level on Logger[org.mariadb] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.mariadb] to true
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache] to INFO
11:11:14,636 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating INFO level on Logger[org.apache] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.apache] to true
11:11:14,636 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to TRACE
11:11:14,636 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@25e2ab5a - Propagating TRACE level on Logger[ROOT] onto the JUL framework
11:11:14,636 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [stdout] to Logger[ROOT]
11:11:14,636 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@35e5d0e5 - End of configuration.
11:11:14,637 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@73173f63 - Registering current configuration as safe fallback point


 _   ___   _______  _____  ___  ____________ 
| | / / | | | ___ \|  _  |/ _ \ | ___ \  _  \
| |/ /| | | | |_/ /| | | / /_\ \| |_/ / | | |
|    \| | | | ___ \| | | |  _  ||    /| | | |
| |\  \ |_| | |_/ /\ \_/ / | | || |\ \| |/ / 
\_| \_/\___/\____/  \___/\_| |_/\_| \_|___/  
                                             
                                             
 Kuboard     Version:  v4.0.0.0-alpha.03 (vv4.0.0.0-alpha.03)
 Spring Boot Version:  3.2.5 (v3.2.5)

2024-05-30 11:11:14.673 INFO  background-preinit  org.hibernate.validator.internal.util.Version.<clinit>():21 - HV000001: Hibernate Validator 8.0.1.Final
2024-05-30 11:11:14.746 INFO  main  cn.kuboard.KuboardServer.logStarting():50 - Starting KuboardServer vv4.0.0.0-alpha.03 using Java 17-ea with PID 12 (/app/kuboard-server.jar started by root in /app)
2024-05-30 11:11:14.747 INFO  main  cn.kuboard.KuboardServer.logStartupProfileInfo():654 - No active profile set, falling back to 1 default profile: "default"
2024-05-30 11:11:16.005 INFO  main  o.springframework.cloud.context.scope.GenericScope.setSerializationId():282 - BeanFactory id=a521b952-d9d9-3813-9e54-24db0e6ce3fb
2024-05-30 11:11:16.293 INFO  main  o.s.boot.web.embedded.tomcat.TomcatWebServer.initialize():109 - Tomcat initialized with port 8080 (http)
2024-05-30 11:11:16.302 INFO  main  org.apache.coyote.http11.Http11NioProtocol.log():173 - Initializing ProtocolHandler ["http-nio-8080"]
2024-05-30 11:11:16.303 INFO  main  org.apache.catalina.core.StandardService.log():173 - Starting service [Tomcat]
2024-05-30 11:11:16.303 INFO  main  org.apache.catalina.core.StandardEngine.log():173 - Starting Servlet engine: [Apache Tomcat/10.1.20]
2024-05-30 11:11:16.329 INFO  main  o.a.c.core.ContainerBase.[Tomcat].[localhost].[/].log():173 - Initializing Spring embedded WebApplicationContext
2024-05-30 11:11:16.330 INFO  main  o.s.b.w.s.c.ServletWebServerApplicationContext.prepareWebApplicationContext():296 - Root WebApplicationContext: initialization completed in 1510 ms
 _ _   |_  _ _|_. ___ _ |    _ 
| | |\/|_)(_| | |_\  |_)||_|_\ 
     /               |         
                        3.5.5 
2024-05-30 11:11:16.861 INFO  main  com.zaxxer.hikari.HikariDataSource.getConnection():110 - HikariPool-1 - Starting...
2024-05-30 11:11:16.875 WARN  main  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext.refresh():632 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ddlService' defined in URL [jar:nested:/app/kuboard-server.jar/!BOOT-INF/classes/!/cn/kuboard/ddl/DdlService.class]: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, "jdbc:mysql://10.200.200.23:3306/kuboard?serverTimezone=Asia/Shanghai"
2024-05-30 11:11:16.877 INFO  main  org.apache.catalina.core.StandardService.log():173 - Stopping service [Tomcat]
2024-05-30 11:11:16.890 INFO  main  o.s.b.a.logging.ConditionEvaluationReportLogger.logMessage():82 - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-05-30 11:11:16.912 ERROR main  org.springframework.boot.SpringApplication.reportFailure():851 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ddlService' defined in URL [jar:nested:/app/kuboard-server.jar/!BOOT-INF/classes/!/cn/kuboard/ddl/DdlService.class]: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, "jdbc:mysql://10.200.200.23:3306/kuboard?serverTimezone=Asia/Shanghai"
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:962)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
	at cn.kuboard.KuboardServer.main(KuboardServer.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.RuntimeException: Driver com.mysql.cj.jdbc.Driver claims to not accept jdbcUrl, "jdbc:mysql://10.200.200.23:3306/kuboard?serverTimezone=Asia/Shanghai"
	at com.zaxxer.hikari.util.DriverDataSource.<init>(DriverDataSource.java:110)
	at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:326)
	at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:112)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:93)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at cn.kuboard.config.DatabaseIdConfig.sqlMode(DatabaseIdConfig.java:41)
	at cn.kuboard.ddl.DdlService.installDdl(DdlService.java:28)
	at cn.kuboard.ddl.DdlService.afterPropertiesSet(DdlService.java:70)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 21 common frames omitted
```

**Comment by lamking** [comment]
DB_URL="jdbc:mysql://10.200.200.23:3306/kuboard?serverTimezone=Asia/Shanghai"

刚遇到这个问题 去掉双引号即可
